### ISSUE TITLE
how to add a count limit to multiple media selection.

### ISSUE THREAD

**Issue by tech4solitude** [wordpress-mobile/MediaPicker-iOS#114]
I was not able to find the option for the multiple selection count limit. How to add the count limit.
Does this library support that.

**Comment by SergioEstevao** [comment]
This library at the moment doesn't support this, but I can add a feature to it, do you want to limit the total number os assets selected?

**Comment by Punith1234** [comment]
@SergioEstevao  Thanks a lot for response.. Yes i wanted to add the limit on number of images selected...

**Comment by SergioEstevao** [comment]
This can be implemented using the `shouldSelectAsset` callaback and then checking the `selectedAssets property` for the limit you want to implement.
