### ISSUE TITLE
Crash in WPMediaCollectionViewController updateDataWithRemoved:inserted:changed:moved

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/MediaPicker-iOS#128]
We've had quite a few reports for a crash affecting the media picker – something going wrong with the collection view in `-[WPMediaCollectionViewController updateDataWithRemoved:inserted:changed:moved:]`. 

<img width="870" alt="screen shot 2016-11-16 at 14 56 32" src="https://cloud.githubusercontent.com/assets/4780/20352377/f8e92fe6-ac0e-11e6-9e06-5fbc9b7f1084.png">

Possibly-related exceptions:

> Fatal Exception: NSInternalInconsistencyException
attempt to insert item 0 into section 0, but there are only 0 items in section 0 after the update

> Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (2063) must be equal to the number of items contained in that section before the update (2063), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out)

**Comment by frosty** [comment]
Still occurring in 7.2: 

http://crashes.to/s/3c8ed807b27
http://crashes.to/s/8774eb2984c

This is currently one of our biggest crashers.

**Comment by astralbodies** [comment]
Poop. I'll try and get another round of analysis in on this.

**Comment by hypest** [comment]
An 7.3:
http://crashes.to/s/0dd79e4be69

**Comment by SergioEstevao** [comment]
Solved with #182
