### ISSUE TITLE
Manual installation?

### ISSUE THREAD

**Issue by amcastror** [wordpress-mobile/MediaPicker-iOS#162]
Hi, how can I install this manually? Just copy files into my working directory?

Thanks a lot for the help.

**Comment by SergioEstevao** [comment]
Yes, you can just copy all the files inside the Pod folder across to your project.

**Comment by amcastror** [comment]
Thanks.. while I have your attention.. why isn't the library distributed through cocoapods anymore? It stopped at version 0.10.*.

Thanks!

**Comment by SergioEstevao** [comment]
I see version 0.14 here: https://cocoapods.org/pods/WPMediaPicker

**Comment by amcastror** [comment]
Ok, my bad, but still, v1.2.0 isn't. Thanks!

**Comment by SergioEstevao** [comment]
Version 0.12 and 0.13 were also release trough Cocoapods.

**Comment by SergioEstevao** [comment]
You may want to check if your local copy of the pods is updated.

Run this command in your machine to get all the latest version of the pods:

```pod repo update```

**Comment by amcastror** [comment]
Yes, but those are old versions (right?), v1.2.0 isn't.

Sorry if I'm not seeing something here..

**Comment by SergioEstevao** [comment]
But, we never released version v1.2.0 of the WPMediaPicker the latest pod version is 0.14.

Are you by any means referring to the CocoaPods version we are using?

**Comment by amcastror** [comment]
Wow, sorry, I hadn't realize that 0.14 was the last version, sorry for the confusion (I'm closing the issue).

I got confused while looking for [this](https://github.com/wordpress-mobile/MediaPicker-iOS/blob/0.7.3/Pod/Classes/WPALAssetDataSource.h) class. It was last added in tag 0.7.3, do you know why it's not there? I need to put the capture of media first, before the existing media.

Thanks so much for the help!

**Comment by SergioEstevao** [comment]
That class was removed from the library because we stopped supporting the old ALAssetLibrary that is deprecated.

We now support only the Photos library.

To make the capture media first you can use the setting ```showMostRecentFirst```. Set it to true and the capture "cell" will show on the top of the list.

**Comment by amcastror** [comment]
THANKS SO MUCH! Worked like a charm. Thanks for the library!
