### ISSUE TITLE
Video is poor quality - add option to choose video quality

### ISSUE THREAD

**Issue by DavidTomic** [wordpress-mobile/MediaPicker-iOS#165]
### Expected behavior
Have option to choose video quality.

### Actual behavior
Video quality is poor.

### Steps to reproduce the behavior
Start WPNavigationMediaPickerViewController and take video.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 5, ios 9.

I made "hack" and fork this repository and used:
options.deliveryMode = PHVideoRequestOptionsDeliveryModeHighQualityFormat; in method - (WPMediaRequestID)videoAssetWithCompletionHandler:(WPMediaAssetBlock)completionHandler

And also in WPMediaPickerViewController.m I added imagePickerController.videoQuality = UIImagePickerControllerQualityTypeHigh; in method - (void)showMediaCaptureViewController.

**Comment by SergioEstevao** [comment]
Thanks for reporting this, I will follow up with a PR soon with your suggestions.

@astralbodies I think David found the same issue you noticed a while ago.

**Comment by SergioEstevao** [comment]
@DavidTomic just push a PR for this #166
