### ISSUE TITLE
Refactor the multiple options on WPMediaPickerViewController to a single struct/class

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/MediaPicker-iOS#185]
I purpose to refactor/move to an options object, ```WPMediaPickerOptions```, the following attributes :

- ```showMostRecentFirst```
- ```filter```
- ```allowMultipleSelection```
- ```cameraPreviewSize```
- ```preferFrontCamera```
- ```allowCaptureOfMedia```

This will allow to make it easier to add new attributes to it, and reflect them on the classes that use it  like `WPNavigationMediaPickerViewController` and `WPInputMediaPickerViewController`.

The options object could be set on the init methods, but also be changed with a setter method, that will make sure the picker get's updated correctly in a single place.

**Comment by frosty** [comment]
Sounds like a great idea, @sergioestevao!
