### ISSUE TITLE
Allow media preview from the input view

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/MediaPicker-iOS#189]
### Expected behavior
  - When doing a long press on the media picker when is being used on a inputView we should be able to display a force touch preview

### Actual behavior
 - No preview happens

### Steps to reproduce the behavior
 - On the demo app
 - Tap on the text view to activate the custom media inputView
 - Force Touch on asset to start force touch preview
 - Don't see it.

**Comment by bummytime** [comment]
This was addressed in #199. As of right now, there doesn't appear to be a way to leverage force touch from an inputView.

/cc @frosty
