### ISSUE TITLE
WPNavigationMediaPickerController: Add option to exclude group picker from navigation stack.

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/MediaPicker-iOS#210]
@SergioEstevao recently added an option to `WPNavigationMediaPickerController`, `startOnGroupSelector`, which allows the full screen navigation controller picker to be presented with the All Photos (or first album) already selected (bypassing the groups list). The groups / albums list is already pushed onto the navigation stack prior to the first album being selected.

In WPiOS, this is fine for device photos, but is a little weird for the media library (which only has one collection). When cancelling out of the fullscreen picker, the user first has to Back out of the media library collection, then cancel out of the groups list. We should add another option (`omitGroupSelector` ?) to bypass the group selector altogether and never even add the groups list to the navigation controller in the first place.

Example of the current state:

![mediapicker-3](https://user-images.githubusercontent.com/4780/29568074-1b63ee6c-8747-11e7-967f-4cb112ca979b.gif)

**Comment by SergioEstevao** [comment]
@frosty the option is already available on the `WPNavigationMediaPickerController` it's called `showGroupSelector`.

Set it to NO and you will get the result you requested above.
