### ISSUE TITLE
Hide empty albums

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/MediaPicker-iOS#230]
Due to some changes we made to speed up the appearance of the picker, we're currently showing empty albums in the albums list:

![fullsizerender 3](https://user-images.githubusercontent.com/4780/29948900-4acbf488-8ea9-11e7-9dce-95345c03459b.jpg)

We should find a way to hide these empty albums.

**Comment by SergioEstevao** [comment]
Humm, It will be good to try again to do the fetch with limit of 1 to see if it can be done with good performance.

Another alternative will to do an async pass to count all the albums and then update the list...
