### ISSUE TITLE
Update collection cell design for audio & doc files

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/MediaPicker-iOS#245]
Title has it. The issues here include:

* White text is difficult to see.
* Long file names overlap the selection indicator

<img width="482" alt="screen shot 2017-09-28 at 10 30 48 am" src="https://user-images.githubusercontent.com/154014/30975796-c73e02aa-a438-11e7-9964-2d4bb652bf7d.png">

ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/7869#pullrequestreview-65853957

/cc @iamthomasbishop

**Comment by iamthomasbishop** [comment]
Thoughts on something like this?

<img width="269" alt="screenshot 2017-09-28 16 02 38" src="https://user-images.githubusercontent.com/1200432/30990339-7a425bee-a466-11e7-99b7-e6594e3f56ba.png">

* Removes the file type label, instead shows it at the end of the file name (which in this example is truncated at the end of the file name, before the extension)
* Keeps the icon
* Inverts the colors (text/icon are gray-lighten-30 and background is gray-dark) similar to changes that are being made on Android
* File name / label is 12pt gray-lighten-30, regular weight

**Comment by bummytime** [comment]
@iamthomasbishop I think that looks great! I like the inverted color scheme much better. Would you still like the duration of the audio file in the lower right corner?

**Comment by SergioEstevao** [comment]
@bummytime will you take care of this? I can do it today if you don't have the bandwidth.

**Comment by bummytime** [comment]
@SergioEstevao I am on it!
