### ISSUE TITLE
Search bar inset issues

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/MediaPicker-iOS#264]
I've noticed a couple of issues with the new search bar in the media picker:

The bottom scroll / content insets of the collection view don't seem to be adjusted when the keyboard is shown:

![simulator screen shot - iphone 8 - 2017-11-10 at 14 39 34](https://user-images.githubusercontent.com/4780/32677048-dd57ecb6-c654-11e7-88ac-cf8628441d64.png)

Notice the content scrolls down behind the keyboard, and the scroll indicator is hidden behind there too.

Also, the search bar is inset on both sides on the iPhone X in landscape, but I'd expect its background to stretch to the edges of the screen. Compare the current search bar in the media library in WPiOS:

<img width="813" alt="screen shot 2017-11-10 at 20 20 29" src="https://user-images.githubusercontent.com/4780/32676995-a0d0473e-c654-11e7-82e8-244ca9c84492.png">

with the search bar in the media picker:

<img width="812" alt="screen shot 2017-11-10 at 20 17 21" src="https://user-images.githubusercontent.com/4780/32676890-31c2c33a-c654-11e7-8b3a-b5d33e04a02e.png">

cc @etoledom

**Comment by etoledom** [comment]
@frosty, thanks for pointing these issues out! I´ll get down to fixing them right away. 👍

**Comment by etoledom** [comment]
@frosty @SergioEstevao The PR is ready in #265 .

Working on this I noticed that it might be necessary to add a couple of extra methods to the search API:

- A method to let the data source know when the user cancels the search, so it has an opportunity to clean up any search-related state. Possibly called `searchCancelled`.

- A method to let the delegate know that amount of elements displayed changed by a search query. This could be useful to let the controller react to the new element count and, for example, show an empty screen if the search has no results. This could be called `mediaPickerController:didUpdateSearchWithAssetCount:`, similar to the implementation of the media library in the WPiOS App.

If you approve, I can create an issue and start working on it. What do you think? 🤔

**Comment by SergioEstevao** [comment]
> A method to let the data source know when the user cancels the search, so it has an opportunity to clean up any search-related state. Possibly called searchCancelled.

We could also use the current method with a nil argument: `serchFor(nil)`. @frosty what do you prefer?

> A method to let the delegate know that amount of elements displayed changed by a search query. This could be useful to let the controller react to the new element count and, for example, show an empty screen if the search has no results. This could be called mediaPickerController:didUpdateSearchWithAssetCount:, similar to the implementation of the media library in the WPiOS App.

We probably should implement by default a simple no search result screen and let the users of the library replace it? For example Apple on the Photos app does the following:
![img_2579](https://user-images.githubusercontent.com/651601/32723062-ff67614a-c863-11e7-87d1-cdd9730592ac.PNG)


@frosty any preference here?

**Comment by etoledom** [comment]
> We could also use the current method with a nil argument: serchFor(nil).

Yes, the result will be the same. Using `searchFor:` sounds like a better option to keep the API simple. It’s not so explicit, but while it’s well documented it should’t be a problem, right?

> We probably should implement by default a simple no search result screen and let the users of the library replace it?

I like the idea of a dedicated method to manage empty views and a default implementation. It makes the intention a lot clearer.

The `didUpdateSearchWithAssetCount:` might also be useful for other things, but I suppose in most cases it´s not really necessary.

**Comment by frosty** [comment]
I feel like separate search cancelled delegate method might be best... because if the user erases all of the text in the search field but search is still active and the keyboard is up, wouldn't that look the same if we just used `searchFor`? Or would one pass an empty string and one pass `nil`? I think a separate method would be more explicit.

A default no results view sounds fine, although I wouldn't spend too much time on it as it's primarily just going to be for the demo app. :)

I like the sound of `didUpdateSearchWithAssetCount`!

**Comment by SergioEstevao** [comment]
@etoledom I bow to @frosty on this one, let's go for your initial recommendations then.
