### ISSUE TITLE
Extra API needed to know about specific events related to the search bar.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/MediaPicker-iOS#267]
I would be good to have a couple of extra methods in the search API:

- A method to let the data source know when the user cancels the search, so it has an opportunity to clean up any search-related state.
- A method to let the delegate know that the amount of elements displayed changed by a search query. It could be useful to let the controller react to the new element count.

**Comment by etoledom** [comment]
As discussed in #264 , we can add a:

- `searchCancelled` method to let the data source know about this action.
- `didUpdateSearchWithAssetCount:` method to the delegate so the controller can react accordingly.

An extra method suggested by @SergioEstevao  is a dedicated method to ask the delegate about a view to display in an empty screen:
`emptyViewForMediaPickerController:` with a simple default implementation of a UILabel.

**Comment by SergioEstevao** [comment]
@etoledom you have green light to implement these changes 👍
