### ISSUE TITLE
Open capture screen directly

### ISSUE THREAD

**Issue by DavidTomic** [wordpress-mobile/MediaPicker-iOS#297]
Hi,

I am using version 1.0

Is there a way to open capture screen directly?

**Comment by SergioEstevao** [comment]
At the moment no, what is the use case that you are trying to cater for?

**Comment by DavidTomic** [comment]
I have camera and gallery buttons in my app.

I want to open capture screen directly after pressing camera button.

e.g. Viber has that feature.

**Comment by SergioEstevao** [comment]
But after the image is captured do you want to go back to the camera roll screen? or just receive the captured assets on the callback?
