### ISSUE TITLE
Crash Occurred when opening picker

### ISSUE THREAD

**Issue by StephanWalters** [wordpress-mobile/MediaPicker-iOS#305]
Crash Occurred when opening the picker. It's only happened once, but providing the crashlog:
http://crashes.to/s/c8e25eec50a

##### Tested on [device], iOS [version], WPMediaPicker [version]
- iPhone 
- iOS 11
- WPMediaPicker 1.3

**Comment by SergioEstevao** [comment]
Solved on release 1.3.4
