### ISSUE TITLE
Conform to Community Standards

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/MediaPicker-iOS#315]
To promote consistency across `WordPress-iOS` frameworks & to conform to [recommended community standards](https://github.com/wordpress-mobile/MediaPicker-iOS/community), we should update this repository to include all of the following:

- [X] Description
- [X] README
- [x] Code of conduct
- [X] Contributing
- [X] License
- [x] Issue templates
- [X] Pull request template

We should also modify the PR checks we have in place for consistency with `WordPress-iOS` (e.g., build checks, approval / merge requirements, etc.).

**Comment by SergioEstevao** [comment]
Send some PR's your way @stevebaranski I also update the develop branch merge rules.
