### ISSUE TITLE
Use iOS 14's PHPickerViewController for device media selection

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/MediaPicker-iOS#363]
**Is your feature request related to a problem? Please describe.**
iOS 14 adds a new "Limited" permissions option that complicates the experience a bit:

<a href="https://user-images.githubusercontent.com/3250/104390847-e0cd2f80-54fb-11eb-948e-c7346bd60f1d.jpg"><img src="https://user-images.githubusercontent.com/3250/104390847-e0cd2f80-54fb-11eb-948e-c7346bd60f1d.jpg" width="300"></a>

A prompt is not required as long as the PHPickerViewController is used. See pbArwn-17O-p2 for details and discussions of the permissions prompts.

**Describe the solution you'd like**
We should be using the PHPickerViewController for selecting media from the users' device.

**Describe alternatives you've considered**

**Additional context**
This may need to be part of a bigger project to consolidate the various sources of media pickers into one interface as Android currently does. See pbArwn-1cr-p2

**Comment by SergioEstevao** [comment]
@bjtitus are you proposing to wrap around PHPickerViewController inside the MediaPicker library?

Or replace the uses of the MediaPicker for accessing the users' device with the PHPickerViewController?

We can do that in the main WP apps but we will need to keep a fallback for the iOS 13 devices.

**Comment by bjtitus** [comment]
@SergioEstevao Sorry for the lack of detail. This was mostly a stub for a larger discussion about changes we started discussing for stories: pbD5rk-lL-p2

> are you proposing to wrap around PHPickerViewController inside the MediaPicker library

I was thinking about this change if we switch to a consolidated UI, where WP Media and device photos are in different tabs. So we would wrap `PHPickerViewController` and add something like `WPNavigationMediaPickerViewController` but with multiple datasources with corresponding tabs instead of just one.

<a href="https://user-images.githubusercontent.com/3250/104391220-aca63e80-54fc-11eb-9267-edde2f4048b7.png"><img src="https://user-images.githubusercontent.com/3250/104391220-aca63e80-54fc-11eb-9267-edde2f4048b7.png" width="300"></a>

I'm drafting up a post with some further details.

**Comment by kean** [comment]
Covered in https://github.com/wordpress-mobile/WordPress-iOS/issues/21190. I'm going to close this ticket as a duplicate.
