### ISSUE TITLE
Unable to import Slow Motion Videos from gallery

### ISSUE THREAD

**Issue by prashantimpinge** [wordpress-mobile/MediaPicker-iOS#366]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SergioEstevao** [comment]
Can you provide more detail about the bug? Are you unable to see/select the slow-mo videos? Or are you unable to get the asset information after selection?

**Comment by kean** [comment]
Covered by https://github.com/wordpress-mobile/WordPress-iOS/issues/21190
