### ISSUE TITLE
Add search function when selecting photos from device

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/MediaPicker-iOS#374]
**Is your feature request related to a problem? Please describe.**
Requested in 4397104-zd-woothemes:

> Permissions are on and the photos were added to favorites but they just didn’t show up for some reason. Besides putting them in favorites to find them I can’t figure out any other way to find them without scrolling through the 72,000 images. A search feature in the photo section would help. Standard file loading setting. Not the custom ones like now. And also a search in catalogues area as again I just have to scroll through unreadable kanji results to try and find the category I want. 

**Describe the solution you'd like**
Add a search function when selecting photos from iOS devices like what's available on WPAndroid.

**Comment by kean** [comment]
Covered by https://github.com/wordpress-mobile/WordPress-iOS/issues/21190
