### ISSUE TITLE
is license MIT or GPL?

### ISSUE THREAD

**Issue by dredenba** [wordpress-mobile/MediaPicker-iOS#64]
I started using this with the impression that it is under the MIT license.
The description says MIT license but also mentions GPL, so I am confused. The cocoa pod (v 0.4.5, https://cocoapods.org/pods/WPMediaPicker ) indicates that it is under the MIT license

Is this project allowed to be used in iOS apps submitted to the AppStore? My understanding of the licensing means that GPL or LGPL licensed software may not be allowed in apps offered through the AppStore.

Can you clarify for me which license is being used?

**Comment by sendhil** [comment]
The license is GPL.

**Comment by dredenba** [comment]
okay thank you for the clarification.
