### ISSUE TITLE
The camera on ios7 is too slow and not smooth. Sometimes it will crash app.

### ISSUE THREAD

**Issue by lealife** [wordpress-mobile/MediaPicker-iOS#72]
It's good on ios 8

**Comment by bummytime** [comment]
@lealife could you provide a little more detail on how to repro?

**Comment by bummytime** [comment]
@lealife is this bug a dup of #73? If not please provide as much detail as possible. Thanks!

**Comment by lealife** [comment]
NO, it's not a dup issue of #73. Sometimes it's too slow when take photo on IOS7. 
"Sometimes it will crash app." this problem is dup of #73

**Comment by SergioEstevao** [comment]
The component now only works on iOS 8 and above so this issue is no longer relevant
