### ISSUE TITLE
iOS9

### ISSUE THREAD

**Issue by LiuHengChina** [wordpress-mobile/MediaPicker-iOS#83]
MediaPicker-iOS  if it can support iOS9

**Comment by LiuHengChina** [comment]
Whether the expiration method will override

**Comment by SergioEstevao** [comment]
@LiuHengChina the media picker supports iOS 9, are you running in any issue using iOS9?

**Comment by LiuHengChina** [comment]
Before using the old version, see a lot of iOS9 method expired. About photokit, it has been resolved

**Comment by SergioEstevao** [comment]
All deprecated methods related to the deprecated AssetLibrary, UIAlertView ad UIPopoverController where remove in version 0.8.0 of the library.
