### ISSUE TITLE
Group picker: "Counting media items..." persists until you make a selection

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/MediaPicker-iOS#86]
Every time you open the media picker, the group picker shows "Counting media items..." under Media Library and that text is not updated until you make a selection and then re-open the group picker.

Steps:
1. Open editor and media picker
2. Tap on "Camera Roll" to open group picker
3. Under Media Library, note the text "Counting media items..." and leave the popover open to wait for that count to appear. The text never changes.
4. Select any group from the group picker, and then re-open the group picker. The Media Library now shows a count.

I'm not sure if that's the expected behavior, but it feels like a bug. The text "Counting media items..." creates an expectation that it will update itself with a count as you wait.

**Comment by SergioEstevao** [comment]
This is fixed on the version 0.7.3 of the component and will be available on version 5.9 of the app.
