### ISSUE TITLE
didReceiveMemoryWarning

### ISSUE THREAD

**Issue by zhujia18** [wordpress-mobile/MediaPicker-iOS#87]
Hi,sometimes i found this picker will receive MemoryWarning, I tested on some devices and two iOS9 device MemoryWarning abort. I guess maybe it's picker bug.
THX for this picker.

![leak](https://cloud.githubusercontent.com/assets/11087900/11215833/2c47164c-8d83-11e5-8886-fe2147da9836.png)
![u f_16f wds94i sjn r](https://cloud.githubusercontent.com/assets/11087900/11232891/9d7a918a-8df2-11e5-83d6-b13955fb47d4.jpg)

**Comment by zhujia18** [comment]
We use it in leanote. https://github.com/leanote/leanote-ios. Thx

**Comment by SergioEstevao** [comment]
This was solved when the code was updated to use the Photos library.
